# Generated by Django 2.1.8 on 2019-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(upload_to='AppShop/img', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodsimg',
            name='img_address',
            field=models.ImageField(upload_to='AppShop/img', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='AppShop/img', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_logo',
            field=models.ImageField(upload_to='AppShop/img', verbose_name='店铺logo'),
        ),
    ]
